#!/bin/sh

# ==============================================================================
# KEENETIC FIREWALL HOOK (DUAL LIST)
# Description: Integrates IPSET blocklists with Keenetic NDM Netfilter.
#              Manages both downloaded lists and local VPN bans.
# ==============================================================================

# 1. EXTERNAL LIST (The 20k+ IP list, managed by external script)
IPSET_MAIN="FirewallBlock"

# 2. LOCAL LIST (Generated by VPN log scan)
IPSET_VPN="VPNBlock"
VPN_BANNED_FILE="/opt/etc/vpn_banned_ips.txt"

# --- SECTION: FILTER TABLE ONLY ---
[ "$table" != "filter" ] && exit 0

# --- LOCAL IPSET INITIALIZATION ---
# Create the VPN set if it doesn't exist (hash:ip because they are single IPs)
ipset create "$IPSET_VPN" hash:ip hashsize 1024 maxelem 65536 -exist 2>/dev/null

# --- RESTORE PERSISTENCE (Crucial on reboot) ---
# If the set is empty but we have a save file, reload IPs
if [ -f "$VPN_BANNED_FILE" ]; then
    # Read the file and silently add IPs to the set
    while read -r ip; do
        [ -n "$ip" ] && ipset add "$IPSET_VPN" "$ip" -exist 2>/dev/null
    done < "$VPN_BANNED_FILE"
fi

# Safety check: if Main set doesn't exist, don't apply its rules (but apply VPNBlock)
MAIN_EXISTS=0
ipset list -n "$IPSET_MAIN" >/dev/null 2>&1 && MAIN_EXISTS=1

# --- A. CLEANUP (Remove old rules) ---
iptables -D INPUT -m set --match-set "$IPSET_MAIN" src -j DROP 2>/dev/null
iptables -D FORWARD -m set --match-set "$IPSET_MAIN" src -j DROP 2>/dev/null
iptables -D INPUT -m set --match-set "$IPSET_VPN" src -j DROP 2>/dev/null
iptables -D FORWARD -m set --match-set "$IPSET_VPN" src -j DROP 2>/dev/null

# Cleanup whitelist
iptables -D INPUT -s 10.0.0.0/8 -j ACCEPT 2>/dev/null
iptables -D FORWARD -s 10.0.0.0/8 -j ACCEPT 2>/dev/null
iptables -D FORWARD -i tun+ -j ACCEPT 2>/dev/null
iptables -D INPUT -i tun+ -j ACCEPT 2>/dev/null
iptables -D INPUT -i lo -j ACCEPT 2>/dev/null
iptables -D INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null
iptables -D FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT 2>/dev/null

# --- B. APPLY RULES (Reverse Order - LIFO) ---

# === FORWARD CHAIN (LAN/VPN -> Internet) ===

# 5. BLOCK: Traffic from main list (Internet)
[ "$MAIN_EXISTS" -eq 1 ] && iptables -I FORWARD -m set --match-set "$IPSET_MAIN" src -j DROP

# 4. BLOCK: Traffic from VPN list (Specific attackers)
iptables -I FORWARD -m set --match-set "$IPSET_VPN" src -j DROP

# 3. WHITELIST: VPN Interfaces (Allow legitimate traffic through tunnel)
iptables -I FORWARD -i tun+ -j ACCEPT

# 2. WHITELIST: Private Networks (LAN)
iptables -I FORWARD -s 10.0.0.0/8 -j ACCEPT

# 1. PRIORITY: Established Connections
iptables -I FORWARD -m state --state RELATED,ESTABLISHED -j ACCEPT


# === INPUT CHAIN (Towards the Router) ===

# 5. BLOCK: Traffic from main list
[ "$MAIN_EXISTS" -eq 1 ] && iptables -I INPUT -m set --match-set "$IPSET_MAIN" src -j DROP

# 4. BLOCK: Traffic from VPN list
iptables -I INPUT -m set --match-set "$IPSET_VPN" src -j DROP

# 3. WHITELIST: VPN Interfaces
iptables -I INPUT -i tun+ -j ACCEPT

# 2. WHITELIST: LAN & Localhost
iptables -I INPUT -s 10.0.0.0/8 -j ACCEPT
iptables -I INPUT -i lo -j ACCEPT

# 1. PRIORITY: Established Connections
iptables -I INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT