#!/bin/sh
# ==============================================================================
# VPN LOG ANALYZER v1.1
# Scans logs for OpenVPN errors and bans IPs.
# Updates the daily diff counter for the Dashboard.
# ==============================================================================

# --- PATHS ---
LOG_FILE="/opt/var/log/messages"
BANNED_IPS_FILE="/opt/etc/vpn_banned_ips.txt"
DIFF_FILE_VPN="/opt/etc/firewall_vpn_diff.dat" # Shared file with dashboard

IPSET_VPN="VPNBlock"
IPSET_MAIN="FirewallBlock" # Name of your main list
LOG_TAG="VPN_Blocker"

# Regex to find OpenVPN errors
SEARCH_PATTERN='TLS handshake failed|Bad encapsulated packet length'

# Create files if they don't exist
touch "$BANNED_IPS_FILE"

# Check log existence
if [ ! -f "$LOG_FILE" ]; then
    logger -t "${LOG_TAG}" "Error: Log file not found: $LOG_FILE. Exiting."
    exit 1
fi

# Extract unique malicious IPs from log
MALICIOUS_IPS=$(grep -i "openvpn" "$LOG_FILE" | grep -E "$SEARCH_PATTERN" | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b" | sort -u)

ip_added_count=0
ip_skipped_count=0

if [ -n "$MALICIOUS_IPS" ]; then
    for IP in $MALICIOUS_IPS; do
        
        # 1. CHECK GLOBAL LIST (Optimization)
        # If IP is already in the main list (FirewallBlock), we ignore it.
        # "ipset test" also checks if IP is inside a blocked subnet (CIDR).
        if ipset test "$IPSET_MAIN" "$IP" >/dev/null 2>&1; then
            ip_skipped_count=$((ip_skipped_count + 1))
            continue # Skip to next IP
        fi

        # 2. CHECK LOCAL LIST
        # If not in global list, check if we already locally banned it.
        if ! grep -qF "$IP" "$BANNED_IPS_FILE"; then
            
            # Add IP to active IPSET (Immediate block)
            ipset add "$IPSET_VPN" "$IP" -exist 2>/dev/null
            
            # Save IP to file for reboot (Persistence)
            echo "$IP" >> "$BANNED_IPS_FILE"
            
            logger -t "${LOG_TAG}" "BANNED: $IP (Not in main list). Added to $IPSET_VPN."
            ip_added_count=$((ip_added_count + 1))
        fi
    done
fi

# --- 3. UPDATE DASHBOARD COUNTER (DELTA CALCULATION) ---
if [ "$ip_added_count" -gt 0 ]; then
    # Read current value from file (generated by update_blocklist or previous runs)
    CURRENT_DIFF=0
    if [ -f "$DIFF_FILE_VPN" ]; then
        CURRENT_VAL=$(cat "$DIFF_FILE_VPN")
        # Check if it is a valid number
        case "$CURRENT_VAL" in
            ''|*[!0-9+\-]*) CURRENT_DIFF=0 ;;
            *) CURRENT_DIFF="$CURRENT_VAL" ;;
        esac
    fi

    # Calculate new total (Current Value + New Banned IPs)
    NEW_DIFF=$((CURRENT_DIFF + ip_added_count))

    # Format with + sign if positive
    if [ "$NEW_DIFF" -ge 0 ]; then NEW_STR="+$NEW_DIFF"; else NEW_STR="$NEW_DIFF"; fi

    # Write new value to file
    echo "$NEW_STR" > "$DIFF_FILE_VPN"
    
    logger -t "${LOG_TAG}" "Dashboard VPN counter updated: $CURRENT_VAL -> $NEW_STR"
fi

# Log summary only if there was activity to reduce noise
if [ "$ip_added_count" -gt 0 ] || [ "$ip_skipped_count" -gt 0 ]; then
    logger -t "${LOG_TAG}" "Scan finished. Added: ${ip_added_count}. Skipped (Already blocked): ${ip_skipped_count}."
fi

exit 0
